### ISSUE TITLE
应用插件后报错 Could not create plugin of type 'UserDevPluginWrapper'.

### ISSUE THREAD

**Issue by wwlwwlwwlwwl** [FledgeXu/ForgeGradleCN#1]
正常使用Forge自带的Gradle就没有问题 但是使用ForgeGradleCN后就会报错 无法使用
##  gradle运行提示
H:\IdeaProject\forge-1.16.4-35.1.37-mdk>gradlew build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* Where:
Build file 'H:\IdeaProject\forge-1.16.4-35.1.37-mdk\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'forge-1.16.4-35.1.37-mdk'.
> Failed to apply plugin [id 'com.otakusaikou.fgcn']
   > Could not create plugin of type 'UserDevPluginWrapper'.
      > com/amadornes/artifactural/api/repository/ArtifactProvider

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

H:\IdeaProject\forge-1.16.4-35.1.37-mdk>
## build.gradle 配置
buildscript {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/public"}
        maven { url = "https://lss233.littleservice.cn/repositories/forgedev" }
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath group: 'com.otakusaikou.fgcn', name: 'ForgeGradleCN', version: '3.+', changing: true
        //classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }
}

apply plugin: 'com.otakusaikou.fgcn'
//apply plugin: 'net.minecraftforge.gradle'
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

## Java环境
H:\IdeaProject\forge-1.16.4-35.1.37-mdk>java -version
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

H:\IdeaProject\forge-1.16.4-35.1.37-mdk>

**Comment by FledgeXu** [comment]
我大概知道为什么了，Forge 团队最近在升级ForgeGradle，修改了其中的一个依赖`ArtifactProvider`导致出问题了。
这里没什么好的办法，建议还是用回FG本身吧。
